# Generated by Django 2.2.4 on 2023-06-25 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
