# Generated by Django 2.2.4 on 2023-06-25 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
